import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css';
import utilStyles from '../styles/utils.module.css'
import Link from 'next/link'
import ResponsiveAppBar from "../components/AppBar";

const name = 'Yu Yoshitani';
export const siteTitle = 'Haru TechLab';

export default function Layout({ children, home }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../public/images/favicon.png" />
      </Head>
      <header className={styles.header}>
        <ResponsiveAppBar />
      </header>
      <main className={styles.main}>{children}</main>
      <footer className={styles.footer}>
        <a>
          ©2022 HARU
        </a>
      </footer>
    </div>
  )
}