import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css';
import Link from 'next/link'
import ResponsiveAppBar from "../components/AppBar";
import * as React from 'react';
import Typography from '@mui/material/Typography';
import { createTheme, ThemeProvider } from '@mui/material/styles';

export const siteTitle = 'Yu TechLab';

const theme = createTheme({
  palette: {
    primary: {
      main: "#303030",
    },
    secondary: {
      main: "#e040fb",
    },
  },
});

export default function Layout({ children }) {
  return (
    <ThemeProvider theme={theme}>
      <div className={styles.container}>
        <Head>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/images/icon.png" />
        </Head>
        <header className={styles.header}>
          <ResponsiveAppBar color="primary" />
        </header>
        <main className={styles.main}>{children}</main>
        <footer className={styles.footer}>
          <a>
            ©2023 YU
          </a>
        </footer>
      </div>
    </ThemeProvider>
  )
}