import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Link from 'next/link';

import ResponsiveAppBar from "../components/AppBar";

export default function About() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/images/favicon.png" />
            </Head>
            <header>
                <ResponsiveAppBar />
            </header>
            <main className={styles.main}>
                <h1 className={styles.title}>
                    About me
                </h1>

                <p className={styles.description}>
                    こんにちは
                </p>

                <div className={styles.grid}>
                    <p>
                        新卒として修行中。
                        主にPython、AWS、Dockerを用いて開発を行っていました。
                        正月の暇な時間を使って、いつかやろうと思っていたWebページ作成を作ってみました。
                        結構楽しい。
                        当ブログには、趣味や学んだことを趣味や学んだことをはき出して行こうと思います。
                    </p>
                </div>
            </main>

            <footer className={styles.footer}>
                <a>
                    ©2022 HARU
                </a>
            </footer>
        </div>
    )
}
