import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Link from 'next/link';
import ResponsiveAppBar from "../components/AppBar";
import MediaCard from "../components/card";

export default function Home() {
  {
    return (
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/images/favicon.png" />
        </Head>
        <header>
          <ResponsiveAppBar />
        </header>
        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to my lab!
          </h1>

          <p className={styles.description}>
            のほほんとした日常を吐き出す場所
          </p>

          <div className={styles.grid}>
            <a href="/trip" className={styles.card}>
              <h2>Trip &rarr;</h2>
              <p></p>
            </a>
            <a href="/engineering" className={styles.card}>
              <h2>Engineering &rarr;</h2>
              <p></p>
            </a>
            <a href="/life" className={styles.card}>
              <h2>Life &rarr;</h2>
              <p></p>
            </a>
          </div>
        </main>

        <footer className={styles.footer}>
          <a>
            ©2022 HARU
          </a>
        </footer>
      </div>
    )
  }
}